services:
  resourcia.api:
    image: ${DOCKER_REGISTRY-}resourciaapi
    container_name: resourcia.api
    build:
      context: .
      dockerfile: Resourcia.Api/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - resourcia.db

  resourcia.db:
    image: postgres:latest
    container_name: resourcia.db
    environment:
      - POSTGRES_USER=resourcia
      - POSTGRES_PASSWORD=ResourciaPassword123!
      - POSTGRES_DB=resourciadb
    ports:
      - "5432:5432"
    volumes:
      - ./.containers/resourcia-db:/var/lib/postgresql/data
